// import { Geist, Geist_Mono, Jost } from "next/font/google";
// import { Roboto, Open_Sans, Lato, Poppins } from "next/font/google";
// import "./globals.css";
// import Header from "./header/Header";
// import Footer from "./footer/Footer";
// import ReduxProvider from "./ReduxProvider";
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";
// import { Link } from "lucide-react";

// export const roboto = Roboto({
//   subsets: ["latin"],
//   weight: ["400", "500", "700", "900"], // ✅ only available weights
//   variable: "--font-roboto",
// });

// export const openSans = Open_Sans({
//   subsets: ["latin"],
//   weight: ["400", "600", "700", "800"], // ✅ valid Open Sans weights
//   variable: "--font-open-sans",
// });

// export const lato = Lato({
//   subsets: ["latin"],
//   weight: ["400", "700", "900"], // ✅ only valid Lato weights
//   variable: "--font-lato",
// });

// export const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700", "800", "900"], // ✅ valid Poppins weights
//   variable: "--font-poppins",
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const jost = Jost({
//   subsets: ["latin"], // or ['latin','latin-ext']
//   weight: ["300", "400", "500", "600", "700"], // only include what you need
//   variable: "--font-jost", // creates a CSS var you can use in Tailwind/CSS
//   display: "swap",
// });
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Spreadnext — Where Careers Meet Community",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/spreads.svg", // ✅ path from public folder
//   },
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${jost.variable} ${roboto.variable}, ${openSans.variable}, ${lato.variable} ${poppins.variable}`}
//       >
//         <ReduxProvider>
//           <div style={{ paddingTop: "35px" }}>
//             <Header />
//           </div>
//           {children}
//           <Footer />
//           <ToastContainer
//             position="top-right"
//             autoClose={3000}
//             hideProgressBar={false}
//             newestOnTop
//             closeOnClick
//             rtl={false}
//             pauseOnFocusLoss
//             draggable
//             pauseOnHover
//             theme="colored"
//           />
//         </ReduxProvider>
//       </body>
//     </html>
//   );
// }


// // app/layout.jsx
// import { Geist, Geist_Mono, Jost } from "next/font/google";
// import { Roboto, Open_Sans, Lato, Poppins } from "next/font/google";
// import "./globals.css";
// import Header from "./header/Header";
// import Footer from "./footer/Footer";
// import ReduxProvider from "./ReduxProvider";
// import { ToastContainer } from "react-toastify";
// import "react-toastify/dist/ReactToastify.css";

// // Fonts config
// export const roboto = Roboto({
//   subsets: ["latin"],
//   weight: ["400", "500", "700", "900"],
//   variable: "--font-roboto",
// });

// export const openSans = Open_Sans({
//   subsets: ["latin"],
//   weight: ["400", "600", "700", "800"],
//   variable: "--font-open-sans",
// });

// export const lato = Lato({
//   subsets: ["latin"],
//   weight: ["400", "700", "900"],
//   variable: "--font-lato",
// });

// export const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700", "800", "900"],
//   variable: "--font-poppins",
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// const jost = Jost({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"],
//   variable: "--font-jost",
//   display: "swap",
// });
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Spreadnext — Where Careers Meet Community",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/spreads.svg",
//   },
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${jost.variable} ${roboto.variable} ${openSans.variable} ${lato.variable} ${poppins.variable} bg-[#0A0F14]`}
//       >
//         <ReduxProvider>
//           {/* Fixed Header */}
//           <div style={{ paddingTop: "55px" }}>
//             <Header />
            
//           </div>

//           {/* Page Content */}
//           {children}

//           {/* Footer */}
//           <Footer />

//           {/* Toast */}
//           <ToastContainer
//             position="top-right"
//             autoClose={3000}
//             hideProgressBar={false}
//             newestOnTop
//             closeOnClick
//             rtl={false}
//             pauseOnFocusLoss
//             draggable
//             pauseOnHover
//             theme="colored"
//           />
//         </ReduxProvider>
//       </body>
//     </html>
//   );
// }


// app/layout.jsx

import { Geist, Geist_Mono, Jost } from "next/font/google";
import { Roboto, Open_Sans, Lato, Poppins } from "next/font/google";
import "./globals.css";

import ReduxProvider from "./ReduxProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import MainLayout from "./MainLayOut";
// ================= Fonts =================
export const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  variable: "--font-roboto",
});
export const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  variable: "--font-open-sans",
});
export const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-lato",
});
export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const jost = Jost({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-jost",
  display: "swap",
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ================= Metadata =================
export const metadata = {
  title: "Spreadnext — Where Careers Meet Community",
  description: "Generated by create next app",
  icons: { icon: "/spreads.svg" },
};

// ================= Root Layout =================
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jost.variable} ${roboto.variable} ${openSans.variable} ${lato.variable} ${poppins.variable} bg-[#0A0F14]`}
      >
        <ReduxProvider>
          <MainLayout>{children}</MainLayout>
          <ToastContainer position="top-right" autoClose={3000} theme="colored" />
        </ReduxProvider>
      </body>
    </html>
  );
}